steps:
  - name: gcr.io/cloud-builders/wget
    id: firebase
    args:
      - '--quiet'
      - '-O'
      - firebase
      - 'https://firebase.tools/bin/linux/latest'

  - name: gcr.io/cloud-builders/npm
    id: install
    args:
      - i
    dir: functions
    waitFor:
      - firebase

  - name: gcr.io/cloud-builders/npm
    id: build
    args:
      - run
      - build
    dir: functions
    waitFor:
      - install
  
  - name: node
    id: deploy
    waitFor:
      - "build"
    entrypoint: "bash"
    args:
      - '-c'
      - |
        ./firebase deploy --only functions

  - name: gcr.io/cloud-builders/gcloud
    id: configure
    waitFor:
      - "deploy"
    entrypoint: "bash"
    args:
      - '-c'
      - |
        chmod a+x ./scripts/setupFunctions.sh
        ./scripts/setupFunctions.sh
  