steps:
  - name: gcr.io/cloud-builders/wget
    id: firebase
    args:
      - "--quiet"
      - "-O"
      - firebase
      - "https://firebase.tools/bin/linux/latest"

  - name: gcr.io/cloud-builders/npm
    id: install
    args:
      - i
    dir: functions
    waitFor:
      - firebase

  - name: gcr.io/cloud-builders/npm
    id: build
    args:
      - run
      - build
    dir: functions
    waitFor:
      - install

  - name: gcr.io/cloud-builders/npm
    id: e2e testing
    args:
      - run
      - test-e2e
    secretEnv: ['NOTION_TOKEN', 'TODOIST_TOKEN']
    dir: functions
    waitFor:
      - build

  - name: node
    id: deploy
    waitFor:
      - "e2e testing"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        chmod a+x ./firebase
        ./firebase deploy --only functions

  - name: gcr.io/cloud-builders/gcloud
    id: configure
    waitFor:
      - "deploy"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        apt update && apt install jq -y 
        chmod a+x ./scripts/setupFunctions.sh
        ./scripts/setupFunctions.sh

availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_NUMBER/secrets/NOTION_TOKEN/versions/1
    env: 'NOTION_TOKEN'
  - versionName: projects/$PROJECT_NUMBER/secrets/TODOIST_TOKEN/versions/1
    env: 'TODOIST_TOKEN'
